import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { AppBar, Box, Button, Toolbar, Typography } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import type { Metadata } from 'next'
import theme from '../theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <AppBar
                position="fixed"
                sx={{ zIndex: 1250, borderBottom: 2, borderColor: 'grey.200' }}
                elevation={0}
              >
                <Toolbar sx={{ backgroundColor: 'background.paper' }}>
                  <Box
                    sx={{
                      width: '100%',
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                    }}
                  >
                    <Typography variant="h6" sx={{ color: 'text.primary' }}>
                      Lists App
                    </Typography>
                    <Box>
                      <SignedOut>
                        <SignInButton>
                          <Button variant="contained">Sign in</Button>
                        </SignInButton>
                      </SignedOut>
                      <SignedIn>
                        <UserButton />
                      </SignedIn>
                    </Box>
                  </Box>
                </Toolbar>
              </AppBar>
              <Box component="main" sx={{ mx: 2, my: 2 }}>
                <Toolbar />
                {children}
              </Box>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
